language: cpp

env:
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=ON -DOPTION_BUILD_TESTS=ON"
    - OMP_NUM_THREADS=2

matrix:
  include:

# xcode 9.1 has no proper openMP support
#    - os: osx
#      osx_image: xcode9.1
#      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug


# clang needs a little hint to find its own omp library
    - os: linux
      compiler: clang
      env:
        - CMAKE_CONFIGURATION=release BUILD_DIR=build
        - LD_LIBRARY_PATH=/usr/local/clang/lib

    - os: linux
      compiler: clang
      env:
        - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug
        - LD_LIBRARY_PATH=/usr/local/clang/lib

# ubuntu 14.04 (travis default) ships with too old gcc; updating is ugly
    - os: linux
      compiler: gcc
      env:
        - CMAKE_CONFIGURATION=release BUILD_DIR=build
        - MATRIX_EVAL="CC=gcc-5 CXX=g++-5"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: windows
      env:
        - CMAKE_CONFIGURATION=release BUILD_DIR=build
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"

    - os: windows
      env:
        - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin"; fi
  - chmod +x ./configure
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
